### ISSUE TITLE
whatever

### ISSUE THREAD

**Issue by alanga48** [alanga48/timeclock#1]

**Comment by rreynier** [comment]
excellent work!

**Comment by alanga48** [comment]
@rreynier Haha! I was trying to remember what their issues interface looks like :)

**Comment by rreynier** [comment]
Lol I figured.  I was subscribed to this repo funny enough so I got an email ;)

**Comment by alanga48** [comment]
Lol I was wondering if that might happen. Thanks for making me laugh!
